set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

SET(CMAKE_C_COMPILER   /opt/riscv/bin/riscv64-unknown-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER  /opt/riscv/bin/riscv64-unknown-linux-gnu-g++)

set(CMAKE_SYSROOT /opt/riscv/sysroot)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)