add_library(optimization INTERFACE)

if(MSVC)
    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        target_compile_options(optimization INTERFACE /Od /Zi)
    else()
        target_compile_options(optimization INTERFACE /O2 /Oi /GL /Gy)
        target_link_options(optimization INTERFACE /LTCG)
    endif()
else()
    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        target_compile_options(optimization INTERFACE -O0 -g)
    else()
        target_compile_options(optimization INTERFACE -O3 -fstrict-aliasing -fomit-frame-pointer)
        target_compile_options(optimization INTERFACE -flto)
        target_link_options(optimization INTERFACE -flto)
        target_compile_definitions(optimization INTERFACE NDEBUG)
    endif()
endif()

