add_library(optimization INTERFACE)

set(NO_LTO OFF CACHE BOOL "Disable Link Time Optimization")
if (NOT NO_LTO AND NOT CMAKE_BUILD_TYPE MATCHES "Debug")
    set_property(TARGET optimization PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
endif()

if(MSVC)
    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        target_compile_options(optimization INTERFACE /Od /Zi)
    else()
        target_compile_options(optimization INTERFACE /O2 /Oi /GL /Gy)
        target_link_options(optimization INTERFACE /LTCG)
    endif()
else()
    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        target_compile_options(optimization INTERFACE -O0 -g)
    else()
        target_compile_options(optimization INTERFACE -O3 -fstrict-aliasing -fomit-frame-pointer)
        target_compile_definitions(optimization INTERFACE NDEBUG)
    endif()
endif()

