add_library(target INTERFACE)

set(TARGET_ARCH "" CACHE STRING "Target architecture (SSE2, AVX, AVX2, AVX512)")
if(MSVC)
    if (TARGET_ARCH)
        message(STATUS "MSVC detected. Using target arch: ${TARGET_ARCH}")
        if(TARGET_ARCH STREQUAL "SSE2")
            target_compile_options(target INTERFACE /arch:SSE2)
        elseif(TARGET_ARCH STREQUAL "AVX")
            target_compile_options(target INTERFACE /arch:AVX)
        elseif(TARGET_ARCH STREQUAL "AVX2")
            target_compile_options(target INTERFACE /arch:AVX2)
        elseif(TARGET_ARCH STREQUAL "AVX512")
            target_compile_options(target INTERFACE /arch:AVX512)
        else()
            message(FATAL_ERROR "Unsupported TARGET_ARCH: ${TARGET_ARCH}")
        endif()
    endif()
else()
    target_compile_options(target INTERFACE -march=native)
endif()