name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.compiler_combo.os }}

    strategy:
      fail-fast: false
      matrix:
        compiler_combo:
          - { c: gcc-14, cpp: g++-14, os: ubuntu-latest }
          - { c: clang, cpp: clang++, os: ubuntu-latest }
          - { c: cl, cpp: cl, os: windows-latest }
          - { c: clang, cpp: clang++, os: macos-latest }
        build_type: [Release]

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install GCC 14
        if: runner.os == 'Linux' && matrix.compiler_combo.c == 'gcc-14'
        run: |
          sudo apt update
          sudo apt install -y gcc-14 g++-14

      - name: Install Clang 18 + LLD
        if: runner.os == 'Linux' && matrix.compiler_combo.c == 'clang'
        run: |
          sudo apt update
          sudo apt install -y clang-18 lld-18

      - name: Configure CMake
        run: >
            cmake -B ${{ steps.strings.outputs.build-output-dir }}
            -DCMAKE_C_COMPILER=${{ matrix.compiler_combo.c }}
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler_combo.cpp }}
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
            -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF
            -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --target ChePP

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }}